syntax = "proto3";
//package code generated by devx  DO NOT EDIT.
package   mason.mason6;

option  go_package ="mason/mason6";

message HelloRequest {
    string msg = 1;
}

message HelloReply {
    string msg = 1;
    string code = 2;
}

service Test.Pb {
    rpc SayHello (HelloRequest) returns (HelloReply);
}
